### ISSUE TITLE
Features and plans (roadmap)

### ISSUE THREAD

**Issue by Mr-Auto** [spelunky-fyi/Spelunky2X64DbgPlugin#2]
Features and upgrades i would like to implement in the future
Feel free to add suggestions or disuse anything listed here. If you want to help with anything, let me know

Implementing standard library structs (and other):
- [x] std::map and std::set
- [x] std::list
- [x] std::string
- [x] std::unordered_map and std::unordered_set
- [x] EntityList
- [x] Static arrays
- [x] Add GameAPI view
- [x] Add EntityFactory
- [x] OnHeapPointer
- [ ] Add uColor (used in particle emitter), use background to show color, maybe also similar thing for the Color struct (4 floats)
- [ ] Build in `EmittedParticlesInfo` and add button to show the particles in new window (similar to the overlunky api)

Improvements:
- [x] Add pointer option to fields to not have to add same thing twice (like "StdMap" and "PointerToStdMap"), maybe even getting rid of the `inline_struct_types` and `pointer_types` arrays entirely
- [x] Refactor `Spelunky2.json` - take all the entity classes, `entity_class_hierarchy` and `default_entity_types` to a separate file. (maybe split even more if that would still be a large file)
- [x] Implement pagination for big containers
- [ ] Add right mouse button menu, add "view struct in new window" to it
- [ ] Inline type = adds all the struct fields directly instead of adding tree branch
- [ ] Allow click in entity memory map (go to the address)
- [ ] StdString make the struct reflect the mode (SSO vs just pointer)
- [ ] Color function signature in vtable view
- [ ] Clear comparison option (entity)
- [x] Allow comparison in db's just like when dropping entity for comparison (add second search box for the comparison index?)
- [ ] String table - add button so see the hex values instead of string
- [ ] String table- look for a way to display icons
- [x] Entity memory tab - make the entity and comparison memory scroll together
- [x] Add "Expand" text in the value field for the structs from json
- [x] Delta - add some sort of prefix when it's pointer (so the delta/offset starts from 0 again)
- [ ] In vtable view - highlight the common 3: just return, return 0 or return 1
- [x] Journal page - make use of `JournalPagePointer`, always load it and then the rest from the desired page (similar to entity subclass)
- [x] Databases - display flag names in comparisons, hide empty, maybe also add separate combo box for the flags (right now for entitydb it's kind of a mess becouse of all the flags)
- [ ] Rename room-code to room-templates, update the json for the missing names from the overlunky api
- [x] Entity: view as - add reset to default
- [ ] Add option to label all records in database
- [ ] Add role type for "was initialized" and update pointers on open, not when refreshing the tree view for the first time
- [x] Compare float and double as raw hex value since values like infinity are always not equal
- [x] Add offset/delta column to the vtable view
- [x] Add comments to the vtable view
- [x] Add option/dialog for editing strings
- [x] Show hex value for bad pointers

Fixes and optimizations:
- [x] Parsing json errors display only once right now - if you have more than one error in the json file, you fix it and use "Reload JSON" it won't show the message box again nor will it print the error in log
- [x] Optimize the level view for entities
- [x] Theme info in state - display hex value ()
- [x] Limit the max size of entity in the entity memory tab
- [x] Look at the build in types like `EntityPointer`, `EntityUID`, `EntityDBID` etc. as they seem to cause lag when having a lot of them refresh
- [x] General code optimizations
- [ ] Potentially: since a lot of strings are kind of constant, just saved from json parser, change std::string to string_view (build custom storage for the actual string to be able to refer them with string_view), maybe even add custom type to mark that the strings are null terminated?
- [x] Reduce the use of `std::unordered_map`, don't think the code needs dynamically add/remove stuff from them, which is the main point of using unordered_map over other containers, maybe instead implement simple vector_map ?
- [x] Memory leak? - when opening any window (State, Entities, LevelGen, GameManager etc.) x64dbg seam to accumulate more and more memory and that memory doesn't seam to go down
- [x] Drop entity for comparison - allow only pointers (maybe even only entity pointer)
- [ ] Clicking into Code pointer does not update module to "Spel2.exe" name in the program header if it was previously different

New functionality:
- [ ] Add option to export/import labels and comments as json file
- [x] Add settings tab/window/menu
    - [x] Hide empty flags, add option to show them
    - [x] Add option to show fields with `skip` type
- [ ] For the 2D arrays in layer (mostly thinking EntityRegions) add level view with clickable regions

**Comment by Mr-Auto** [comment]
Moved from zappatic branch, Already marked stuff done in the PR, also added more ideas
